[package]
name = "cronet-rs"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Cronet bindings for Rust"

[dependencies]
bytes = "1.0"
futures = "0.3"

[build-dependencies]
bindgen = "0.70"